### ISSUE TITLE
Type not found : com.haxepunk.tmx.TmxEntity

### ISSUE THREAD

**Issue by DaVince** [HaxePunk/tiled#34]
I realize that this is not a forum and I'm probably doing something dumb, but I couldn't figure out why I can't use the library, and Google isn't much help. Whenever I include the library and then do `lime test <target>`, lime always complains with:

    Type not found : com.haxepunk.tmx.TmxEntity

(Note: I'm currently compiling to the html5 target, but it also complained about flash and neko.)

`haxelib list` properly lists `HaxePunkTmx: [1.0.3]` and the files seem to be properly located in `/usr/lib/haxe/lib/HaxePunkTmx/1,0,3/com/haxepunk/tmx/`, so I have no clue what's up...

**Comment by ibilon** [comment]
By include did you mean you added `<haxelib name="HaxePunkTmx" />` to your project.xml?

If so then it should work, if haxepunk and openfl are found (no other not found errors?) then it's unlikely to be coming from the tools.

**Comment by DaVince** [comment]
I didn't, and now it does compile. Thanks for helping out someone who's still terribly new at this!

**Comment by ibilon** [comment]
Don't worry ;)
I added this to the README here.

**Comment by DaVince** [comment]
Thanks! I also found that you also need to add

    <haxelib name="format" />

when exporting to the html5 target, but lime will properly warn you about this so I dunno if that needs to be added to the instructions too.

**Comment by ibilon** [comment]
I added an include.xml that will automatically add format when using the html5 target.
