### ISSUE TITLE
TmxMap.loadFromFile fails because Tiled ObjectGroup is missing width/height causes 

### ISSUE THREAD

**Issue by boarnoah** [HaxePunk/tiled#37]
Hello, I am trying to use Tiled's objectLayer with objects with custom properties to initalise enemies for my game. Ran into this issue where if you create an object layer tiled doesn't seem to add a width/height tags to that layer.

 ```xml
//an object layer
<objectgroup name="oLayer1">
//a tile layer
<layer name="tLayer1" width="8" height="8">
```
Its easy to resolve by changing objectLayer's xml manually after the fact to read:
 ```xml
//an object layer
<objectgroup name="oLayer1" width="8" height="8">
```
However this is a bit annoying since Tiled keeps overwriting it, and I plan to do most my level editing (enemy/structure placements) using Objects in Tiled =(.

Issue seems to be from  [tiled/com/haxepunk/tmx/TmxObjectGroup.hx, line 31-32]( tiled/com/haxepunk/tmx/TmxObjectGroup.hx )

My tiled version is 0.12.3 and haxepunk/tiled is also up to date.
I'm exporting the maps orthogonal XML.

EDIT: Not sure my approach of building levels by placing enemies in Tiled is a good idea, but thats a whole other story

EDIT: Found this in the project history: [https://github.com/HaxePunk/tiled/commit/bc241763856527eab2adb1cbb7ea6afcdb34a446](https://github.com/HaxePunk/tiled/commit/bc241763856527eab2adb1cbb7ea6afcdb34a446) not sure why its not working at least for me.

EDIT: Well I feel silly, I looked in my project/hxpTmx's version of tmxobjectgroup and it had the older version of the code. I know for sure my copy of the tmxparser is long after december 2014. So this issue seems to be nonexistent in the new code, it would be helpful if someone could tell me the correct way of updating the parser to the latest version from this repo (because it doesn't come with the hxp folder under references when I create project - hxp 2.5.5)

**Comment by ibilon** [comment]
The one on haxelib didn't contain that fix,
I've pushed a new version,
you can update with `haxelib update HaxePunkTmx`
